language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pecl install igbinary; fi"
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then echo 'extension="igbinary.so"' >> ./tests/travis/php.ini; fi"
    - composer self-update

install:
    - composer --prefer-source --dev install
