language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pecl install igbinary; fi"
    - composer self-update

install:
    - composer --prefer-source install

addons:
  code_climate:
    repo_token: a655057018c5d94b8adb8a80f9b00d42ad6b5b6e8eb28fb21c80d793201e9903

after_script:
  - vendor/bin/test-reporter
